### ISSUE TITLE
how to test if password already supplied

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#12]
Hi, I am creating a little GUI for the minibase net utilities, using gtkdialog.

For wifi, it displays the SSIDs, and has a password entry box and a "Connect" button.

The SSIDs are radiobuttons, and if the use chooses one, I would like it if can determine whether a password has already been provided -- if so, will grey-out the password box.

Is there any way to determine if password already applied to a particular SSID?

**Comment by arsv** [comment]
Added stored-psk indicator to `wifi`. That's a nice feature to have anyway, it was there but got removed when I moved to client-side PSK storage.

The test itself is simple, search /var/wifi-psk (or whatever its location is) for an entry with a matching SSID.

I'm not particularly familiar with gtkdialog, but I looked it up and I suspect you are trying to script `wifi`, the client tool. Please understand that it is not the right thing to do, except maybe as a temporary solution, and it should be expected to break at some point. The output `wifi` produces is meant to be human-readable. It is not meant for parsing.

The right way to interact with `wsupp` is via its socket. That protocol is meant for parsing. The GUI tool should not use `wifi`, it should replace `wifi` completely, doing more or less the same but displaying the data using GUI instead of just printing it to stdout. I don't think it can be done with gtkdialog though, it would require writing a proper GTK app.

Also, just in case, keep in mind that SSIDs aren't really strings. Most are, but it's not guaranteed. Per standard, SSID is an arbitrary sequence up to 32 bytes long.

**Comment by bkauler** [comment]
Thanks for the stored-psk indicator.

Yes, you are right about how I am using gtkdialog. Yes, I am parsing the output of 'wifi'.

It is pretty much standard Unix heritage that we are able to parse output of utilities, however, I will treat this as a temporary solution.

I will probably write it in BaCon, using HUG, as this is a quick way of creating GTK GUIs. BaCon is a "BASIC to C Converter" and HUG is "Highlevel Universal GUI". I am quite fond of it, info here:

http://www.basic-converter.org/

http://www.basic-converter.org/hugdoc.html

The author describes BaCon as a "lazy converter" and C code can be stuck in anywhere.

BaCon is off-topic, just thought that I would mention it, in case anyone reading this is interested in an alternative to coding GTK apps directly in C.

**Comment by bkauler** [comment]
I created the GUI, a shell script using gtkdialog. Did a little write-up here, with snapshots:

http://bkhome.org/news/201902/ultrasns-based-on-minibase-utilities.html

It is just the first iteration, needs more work, but basically works. Also, intend to rewrite it, probably in BaCon.

This is in EasyOS, my experimental distribution. Note, the rest of minibase is very interesting, and what I would like to do is build EasyOS, or my other, older, experimental distro, Quirky Linux, based entirely on minibase. Like you did for Artix.

**Comment by bkauler** [comment]
> Also, just in case, keep in mind that SSIDs aren't really strings. Most are, but it's not guaranteed. Per standard, SSID is an arbitrary sequence up to 32 bytes long.

I checked in the webopedia and a couple of other places. SSIDs are defined as up to 32 _alpha-numeric characters_ (including space char):

https://www.webopedia.com/TERM/S/SSID.html

Also, some online references state it must be ascii only.

Interesting, it seems that some people are able to use utf-8, as long as it fits in the 32 bytes. But some report trouble when try to do it, as here:

https://superuser.com/questions/1259156/is-unicode-not-supported-by-my-router

It does look like you are correct about the 32 bytes being anything. It is just that a lot of reference material on the Internet states that it is ascii alphanumeric characters, also it seems some hardware or web-interface will only accept asci.

**Comment by arsv** [comment]
IEEE 802.11-2012 8.4.2.2 SSID element

"When the UTF-8 SSID subfield of the Extended Capabilities element is equal to 1 in the frame that includes the SSID element, the SSID is interpreted using UTF-8 encoding."

I did not bother locating Extended Capabilities (another IE) but I have seen UTF-8 SSIDs in the wild. About a day or two ago, there was an AP in range transmitting a bunch of zeroes  (\x00) as its SSID.

On the protocol level, *nothing* enforces a particular encoding. All IEs are (length, payload) pairs and that's it. In several places 802.11 describes payload of this particular IE as "Octet string, 0-32 bytes".

Hardware has nothing to do with it, these IEs should be pass-through. Any limitations most likely come from the user interface.
