### ISSUE TITLE
wifi hang on connection request

### ISSUE THREAD

**Issue by moinejf** [arsv/minitools#17]
I like your approach of network connections, but I could not make it work for WIFI.

While network scanning works fine, on wifi connect, the process hangs. The traces show that wsupp sends an authenticate message to the WIFI driver, but this one never answers.

I do not know enough about WIFI to understand the reason of the socket switch, but, could there be some problem there?

**Comment by arsv** [comment]
Hangs completely, as in the client tool stops working?

You should still be able to command disconnect (`wifi dc`) even if there were no replies to AUTHENTICATE. And I guess I would need to add some timeout there as well, like it's been done with DISCONNECT.

**Comment by moinejf** [comment]
Yes, 'wifi' stays waiting for a 'wsupp' response.
Then, 'wifi disconnect' says 'not connected' and a new 'wifi connect' says 'already connected'.
So, setting a timeout will not fix the problem.

The problem is the non-response of the WIFI driver. How can I know if the authenticate request arrived to the driver?

**Comment by arsv** [comment]
Some preliminary changes: https://github.com/arsv/minibase/tree/wifi
If possible, try running this branch to see if it reports any useful errors.

> How can I know if the authenticate request arrived to the driver?

Most drivers log important commands like authentication, check `dmesg`.

**Comment by moinejf** [comment]
I tried your changes, and I get 'not implemented' on authenticate.
Doing a seach, I found this answer
 https://stackoverflow.com/questions/32862759/wpa-supplicant-authentication-implementation
And, yes, my driver has no authenticate nor associate command (as given by 'iw phy').

I tried to send a direct 'connect' instead of 'authenticate + associate', but the content should not be correct and the wifi driver stopped working...

**Comment by arsv** [comment]
What kind of wifi chip are you trying to drive?

And by the way, does it work with wpa_supplicant? If so, try running it with `-dd`, it should print which commands it's sending to the driver.

**Comment by moinejf** [comment]
The chip is a broadcom AP6212 on SDIO (my machine is a Banana PI M2+).
Here is the trace:

[wpa.txt](https://github.com/arsv/minibase/files/3104095/wpa.txt)

**Comment by arsv** [comment]
Ok yes so it does indeed send CONNECT right away, without AUTHENTICATE or ASSOCIATE. I'm not yet sure how to detect this kind of driver, I'll need to check wpa_supplicant sources. But at least it looks like the difference is minor and there should be no problem supporting this in `wsupp`.

And I think I will probably get me a test device, maybe even by this weekend, so I should be able to test it myself. RPi Zero W apparently has a similar wifi chip, BCM43438 (vs BCM43430 in Banana Pi M2). Same series, same driver, so I think they should behave the same.

**Comment by rofl0r** [comment]
any plans to support TKIP, btw ?

**Comment by arsv** [comment]
@rofl0r please open an issue for that. Supporting TKIP is a much more difficult decision than adding a minor variation to the connect sequence to support a pretty popular family of wifi chips.

**Comment by arsv** [comment]
Ok so I finally got it running on RPi Zero (BCM43438, `brcmfmac`). Supporting CONNECT turned out to be quite easy, making it work with the Broadcom drivers not so much, and I ended up reworking a lot of code there to make sure it doesn't lock up if the driver starts doing something unexpected. It should be much better at catching and reporting errors now.

Few notes based on RPi runs. Bring the interface up (`ip link set wlan0 up` or equivalent) before attempting to scan or connect, you'll get `ENETDOWN` otherwise. The code that could do it within `wsupp` never worked reliably on RPi, and I ended up removing it altogether. And you'll have wait for the RNG to become usable before connecting. This may depend on system configuration, but at least for me on RPi Zero without pre-seeding the RNG it typically takes a couple of minutes. Attempts to connect before RNG is ready will result in `EAGAIN` errors.

I have not run this version much yet, so chances are there will be some minor follow-up fixes, but overall it should be usable.
