### ISSUE TITLE
feature request: support TKIP in wsupp

### ISSUE THREAD

**Issue by rofl0r** [arsv/minitools#18]
sometimes one simply doesn't have a choice, but has to use what the existing hardware provides. there's still a big percentage of TKIP-only routers out there.

**Comment by arsv** [comment]
Ok, so why I'm so reluctant to do this: implementing TKIP means a very real possibility of downgrade attacks.

Right now, `wsupp` cannot do worse than WPA2/CCMP-pairwise simply because it doesn't implement anything else. With TKIP support, it would get the ability to go much worse than CCMP, and I would need to prove that it's secure against downgrade attacks. Which is not going to be an easy task. 802.11 is notoriously bad at resisting downgrades.

If I'd add TKIP, it's not like TKIP users would be able to use it and everyone else would just ignore it. Doing so would potentially compromise link security for all non-TKIP users, even those who aren't aware TKIP exists. Especially those who aren't aware.

Now, wpa_supplicant can afford to support it in large part because they have a config file and TKIP pairwise can be disabled there. It's not like anyone does it, but at least they have this excuse. And also they don't care if they carry some dead code, something that pretty much no-one uses.  There is no config file for wsupp, and I'd like to keep it like that. There's also no build-time configuration, that's intentional as well. I'm not a big fan of carry dead code around either. 

I would much rather prefer to keep TKIP support somehow separated from the main project. But I'm not yet sure how to do that. Maybe keep it in wsup-libc for now. Same with WPA3 by the way.

**Comment by arsv** [comment]
Back to technical stuff, let's at least figure out what exactly needs to be supported. If you are running current wsupp, check whether the APs you are interested in are "WPA" or "2TT". With mainline tools, run "iw dev ... scan" and look for these fragments:

    BSS XX:XX:XX:XX:XX:XX(on wlan0)
            last seen: 210000.000s [boottime]           
            TSF: 39868750646 usec (0d, 11:04:28)
            freq: 2432                    
            beacon interval: 100 TUs                  
            capability: ESS Privacy ShortPreamble ShortSlotTime (0x0431)
            signal: -86.00 dBm
            last seen: 664 ms ago       
            Information elements from Probe Response frame:
            SSID: XXXXXXXX
            Supported rates: 1.0* 2.0* 5.5* 6.0 9.0 11.0* 12.0 18.0
            DS Parameter set: channel 5      
            RSN:     * Version: 1    
                     * Group cipher: TKIP
                     * Pairwise ciphers: TKIP
                     * Authentication suites: PSK
                     * Capabilities: 1-PTKSA-RC 1-GTKSA-RC (0x0000)
            WPA:     * Version: 1        
                     * Group cipher: TKIP    
                     * Pairwise ciphers: TKIP    
                     * Authentication suites: PSK      

If it's got the "RSN" section, it's WPA2 TKIP/TKIP or "2TT" in wsupp terms.
If it's only got the "WPA" section, it's WPA1.
There's a huge difference in terms of the effort necessary even though both are TKIP.

**Comment by rofl0r** [comment]
oh, i forgot that wsupp doesn't support wpa1 either. i added support for that in wpakey, which was trivial: https://github.com/rofl0r/wpakey/commit/2041964781c9dab72115bcae0d97b2627bbf4673 . but yeah, i'd like to have support for both wpa1 tkip and wpa2 tkip. what would be the difference between the two ?

**Comment by rofl0r** [comment]
oh, it seems there was more to supporting wpa1: https://github.com/rofl0r/wpakey/commit/693bcd9c5dd383a2f89b3cc2a862805a94fa5de9

**Comment by arsv** [comment]
> what would be the difference between the two ?

WPA2 TKIP is just another option in RSN IEs. It does need a different key wrap and a different MIC, but otherwise it's still RSN and it's reasonably well described in 802.11-2012.

WPA1, I have no idea where it is described. So I would probably have to dig through `wpa_supplicant` code and hope to maybe one day find an AP to test it against that is indeed a WPA1 device and not a later WPA2 capable thing that just happens to advertise WPA1 because somebody did not bother to configure hostapd properly.
