### ISSUE TITLE
ipcfg is missing

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#3]
Hi, I am trying to understand how the networking utilities work.

Using latest minibase source from github (2019-02-4), reading net2/README, it refers to 'ipcfg'. However, that has been removed.

What did it do, and what replaces it?

Also, I have not understood how profiles get created. Perhaps it doesn't help that I am reading the net2/README file, which pertains to the older utilities!

I see that there is "ifctl eth0 mode lan", but where would that get called?

Well, I did this:

```
# ifmon
+++ identify eth0
+++ identify eth1
+++ identify wlan0
```

...but don't know where to go from there. I have eth0, and all that I would normally do is bring it up and run the dhcp client:

```
# ifconfig eth0 up
# dhcpcd eth0
```

I did create /etc/net/mode-lan0, with this:

```
#!/bin/sh
echo "+++ mode-lan0 $1"
ifctl $1 auto-dhcp
```

But that doesn't get called, so obviously I have not assigned "lan0" as profile to eth0.

Any advice greatly appreciated, and excuse me if I have been incredibly dumb not understanding something obvious!

**Comment by arsv** [comment]
`ipcfg` is now called `ip4addr`. It's a tool for configuring static IP on a device. Originally it was meant to be a simplified `ifconfig` but that idea got dropped. 

> I see that there is "ifctl eth0 mode lan", but where would that get called?

This should be called with `ifmon` already running. It sets current mode for device immediately (making ifmon run `mode-lan` on the device), and also saves it as persistent configuration, so that the next time this device appears `ifmon` would do that automatically.

The rest is correct, you just need to run `ifctl eth0 mode lan0` once.

Persistent configuration is saved in ./var/interfaces, check it after doing ifctl mode. The first field is profile name and the second is device id.

**Comment by bkauler** [comment]
Hi, yes, I looked at your source, and discovered /var/interfaces, and also recognized that 'ifctl eth0 mode lan0' would be run just once (after ifmon is started).

I conducted an experiment, and did get it running, but there are some issues. Firstly here are some scripts:

/etc/net/identify

```
#!/bin/sh
echo "+++ identify $1"
ifctl $1 identify
```

/etc/net/mode-lan0

```
#!/bin/sh
echo "+++ mode-lan0 $1"
ifctl $1 auto-dhcp
```

/etc/net/conf-request

```
#!/bin/sh
echo "+++ conf-request $1"
dhcp $1 request
```

/etc/net/dhcp-gw

```
#!/bin/sh
echo "+++ dhcp-gw $@"
```

/etc/net/dhcp-dns

```
#!/bin/sh
echo "+++ dhcp-dns $@"
```

I have got 'ifmon' in the path, running as root, did the following:

```
# mkdir /run/ctrl
# ifmon &
[1] 5676
# +++ identify eth1
+++ identify eth0
+++ identify wlan0

# ifctl eth0 id
pci-0000:04:00.0
# ifctl eth0 mode lan0
# +++ mode-lan0 eth0

# cat /var/interfaces
lan0pci-0000:04:00.0
# ifconfig eth0 up
# +++ conf-request eth0
dhcp: discover: ETIMEDOUT
+++ conf-request eth0
+++ conf-request eth0
+++ dhcp-gw 192.168.1.1
+++ dhcp-dns 192.168.43.1 168.126.63.2
dhcp: discover: ETIMEDOUT

# ping google.com
ping: bad address 'google.com'
# echo -e 'nameserver 192.168.43.1\nnameserver 168.126.63.2' > /etc/resolv.conf
# ping google.com
PING google.com (172.217.25.142): 56 data bytes
64 bytes from 172.217.25.142: seq=0 ttl=50 time=81.806 ms
```

There are three issues in the above. 

Firstly, I had to manually bring up interface eth0. Shouldn't 'ifmon' do this? A program like NetworkManager brings them up, then examines the interfaces to see if they are "live".

Secondly, 'dhcp' worked, but why has it reported that "discover: ETIMEDOUT" the second time?

Thirdly, had no Internet, had to write the nameservers to /etc/resolv.conf. As you can see above.

Regards,
Barry

**Comment by bkauler** [comment]
Ah, perhaps, for issue-3, I have to write to /etc/resolv.conf in script /etc/net/dhcp-dns!

Something like this:

```
#!/bin/sh
echo "+++ dhcp-dns $@"
[ "$1" == "" ] && exit
echo "#written by /etc/net/dhcp-dns" > /etc/resolv.conf
for aIF in $@
do
 echo "nameserver ${aIF}" >> /etc/resolv.conf
done
```

**Comment by bkauler** [comment]
Regarding issue-1, would it be appropriate to bring up the interface in /etc/net/mode-lan0, like this?:

```
#!/bin/sh
echo "+++ mode-lan0 $1"
ifconfig $1 up
ifctl $1 auto-dhcp
```

**Comment by arsv** [comment]
issue-1: yes, if it needs to be brought up it has to be done in the profile script. ifmon will not do it on its own.

issue-3: yes, that's correct as well.

The scripts in net2/etc/ are stubs meant for debugging ifmon, without affecting the rest of the system. That's why all of them are basically echo "script $0 has been called". For something usable, all of them should be replaced with whatever commands are appropriate for a given system.

**Comment by bkauler** [comment]
Probably this issue should be closed. Doing that now.

I see today that 'ifcfg' is back, good.
